version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgresql17_v7
    environment:
      POSTGRES_USER: prudence
      POSTGRES_PASSWORD: prudence
      POSTGRES_DB: enquetejudiciaire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  server:
    build: ./server
    container_name: server
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  frontend:
    image: node:20
    container_name: react_build
    working_dir: /app
    volumes:
      - ./front:/app
    command: sh -c "npm install && npm run build"
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    container_name: react_front
    ports:
      - "3000:80"
    volumes:
      - ./front/build:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
  pgdata:
